{% set name = "py-cordex" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 694e1a376d83159b0b4dfd4e21de4c7f40e791e8d7f65bc84126e4abd551f5e2
  
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm

  run:
    - python >=3.8
    - numpy >=1.17
    - pooch >=1.0
    - xarray >=0.15, !=2023.9.0
    - cf_xarray >=0.8
    - pyproj >=3.3.0
    - setuptools >=40.4

test:
  imports:
    - cordex
  requires:
    - pytest

about:
  home: https://github.com/euro-cordex/py-cordex
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: creation of cordex grids
  doc_url: https://py-cordex.readthedocs.io
  dev_url: https://github.com/euro-cordex/py-cordex

extra:
  recipe-maintainers:
    - larsbuntemeyer
