{% set name = "py-cordex" %}
{% set version = "0.10.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ad421fa6783e590cf0331282bec44d6aaa460db64e60d9d05366f815f4fd8020

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm

  run:
    - python >={{ python_min }}
    - numpy >=1.17
    - pooch >=1.0
    - xarray >=0.15, !=2023.9.0
    - cf_xarray >=0.8
    - pyproj >=3.3.0
    - setuptools >=40.4

test:
  imports:
    - cordex
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/euro-cordex/py-cordex
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: creation of cordex grids
  doc_url: https://py-cordex.readthedocs.io
  dev_url: https://github.com/euro-cordex/py-cordex

extra:
  recipe-maintainers:
    - larsbuntemeyer
